import crypto from "crypto";

// Public key — generated by scripts/generate-keypair.py
// This is safe to embed in the app (only verifies, cannot sign)
const PUBLIC_KEY_B64 = "tZZqYAN2MUsHsh4VXPKRby0Uwrpq4Na+l5thttRzjOY=";

export interface LicensePayload {
  app_id: string;
  edition: string;
  modules: string[];
  customer_id: string;
  expires_at: string;
}

export interface LicenseResult {
  valid: boolean;
  payload?: LicensePayload;
  error?: string;
  graceRemaining?: number;
}

const GRACE_PERIOD_DAYS = 7;
const MS_PER_DAY = 86_400_000;

function base64urlDecode(input: string): Buffer {
  let base64 = input.replace(/-/g, "+").replace(/_/g, "/");
  const pad = base64.length % 4;
  if (pad === 2) base64 += "==";
  else if (pad === 3) base64 += "=";
  return Buffer.from(base64, "base64");
}

export function verifyLicense(key: string): LicenseResult {
  if (!key || key.trim().length < 10) {
    return { valid: false, error: "Chave vazia ou muito curta" };
  }

  const parts = key.trim().split(".");
  if (parts.length !== 3) {
    return { valid: false, error: "Formato inválido — esperado JWT (3 partes)" };
  }

  // Verify Ed25519 signature using Node.js native crypto
  try {
    const message = Buffer.from(`${parts[0]}.${parts[1]}`);
    const signature = base64urlDecode(parts[2]);
    const rawPublicKey = Buffer.from(PUBLIC_KEY_B64, "base64");

    const publicKeyObj = crypto.createPublicKey({
      key: Buffer.concat([
        Buffer.from("302a300506032b6570032100", "hex"),
        rawPublicKey,
      ]),
      format: "der",
      type: "spki",
    });

    const valid = crypto.verify(null, message, publicKeyObj, signature);
    if (!valid) {
      return { valid: false, error: "Assinatura inválida — chave não é autêntica" };
    }
  } catch {
    return { valid: false, error: "Erro ao verificar assinatura" };
  }

  // Decode payload
  let payload: LicensePayload;
  try {
    const json = base64urlDecode(parts[1]).toString("utf-8");
    payload = JSON.parse(json) as LicensePayload;
  } catch {
    return { valid: false, error: "Payload JWT inválido" };
  }

  if (payload.app_id !== "codedocs-desktop") {
    return { valid: false, error: "Licença não pertence a este aplicativo" };
  }

  const expiresAt = new Date(payload.expires_at).getTime();
  if (Number.isNaN(expiresAt)) {
    return { valid: false, error: "Data de expiração inválida" };
  }

  const now = Date.now();
  const daysPastExpiry = (now - expiresAt) / MS_PER_DAY;

  if (daysPastExpiry > GRACE_PERIOD_DAYS) {
    return { valid: false, payload, error: "Licença expirada além do período de graça (7 dias)" };
  }

  const graceRemaining =
    daysPastExpiry > 0
      ? Math.ceil(GRACE_PERIOD_DAYS - daysPastExpiry)
      : undefined;

  return { valid: true, payload, graceRemaining };
}
